---
- name: "reload keyboard config"
  shell: "dpkg-reconfigure keyboard-configuration && systemctl restart keyboard-setup"

- name: reload hostapd
  systemd:
    name: "hostapd"
    enabled: yes
    state: "reloaded"

- name: reload locales
  command: locale-gen
    
- name: restart fan-control
  systemd:
    name: "fan-control"
    enabled: yes
    state: "restarted"
    daemon_reload: yes